observability:
  # Controla logs HTTP
  http:
    enabled: true  # default: true
    excluded-paths:
      - /actuator/health
      - /actuator/metrics
      - /favicon.ico
      - /meu-path-customizado  # adicionar mais se precisar
  
  # Controla observabilidade Kafka
  kafka:
    enabled: true  # default: true
  
  # Controla mascaramento
  masking:
    enabled: true  # default: true
    mask-value: "***MASKED***"  # default: ***MASKED***
    
    # Campos mascarados completamente
    full-mask-fields:
      - password
      - senha
      - token
      - authorization
      - secret
      - apiKey
      - api_key
      - creditCard
      - credit_card
      - cvv
      - pin
    
    # Campos com mascaramento parcial (CPF/CNPJ)
    partial-mask-fields:
      - cpf
      - cnpj
      - documento